import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import QRCode from 'qrcode';
import {Search, MapPin, Clock3, ChevronRight, Plus, Minus, X, ShoppingBag, ArrowLeft, Check, RotateCcw, Copy, Download, Sparkles} from 'lucide-react';
import './styles.css';
const appPath=(path='')=>`${import.meta.env.BASE_URL}${path.replace(/^\//,'')}`;

const img=(id)=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=82`;
const products=[
 {id:1,name:'Classic Burger',cat:'Hamburguesas',price:6.5,desc:'Carne smash, cheddar, lechuga, tomate y salsa de la casa.',image:img('1568901346375-23c9450d58cd')},
 {id:2,name:'Bacon BBQ Burger',cat:'Hamburguesas',price:8,desc:'Doble carne, tocino crocante, cheddar y BBQ ahumada.',image:img('1553979459-d2229ba7433b')},
 {id:3,name:'Double Smash',cat:'Hamburguesas',price:9.5,desc:'Dos medallones dorados, queso americano y pepinillos.',image:img('1600891964599-f61ba0e24092')},
 {id:4,name:'Pizza Pepperoni',cat:'Pizzas',price:10,desc:'Mozzarella fundida, pepperoni y orégano fresco.',image:img('1574071318508-1cdbab80d002')},
 {id:5,name:'Pizza BBQ Chicken',cat:'Pizzas',price:12,desc:'Pollo grill, cebolla morada, mozzarella y BBQ.',image:img('1579751626657-72bc17010498')},
 {id:6,name:'Alitas BBQ',cat:'Platos',price:7.5,desc:'Alitas doradas bañadas en BBQ, con dip ranch.',image:img('1527477396000-e27163b481c2')},
 {id:7,name:'Papas Loaded',cat:'Platos',price:5.5,desc:'Papas crujientes, cheddar, tocino y cebollín.',image:img('1573080496219-bb080dd4f877')},
 {id:8,name:'Limonada Natural',cat:'Bebidas',price:2,desc:'Limón recién exprimido, hierbabuena y hielo.',image:img('1523677011781-c91d1ebe2f3e')},
 {id:9,name:'Coca-Cola',cat:'Bebidas',price:1.5,desc:'Bebida fría 500 ml.',image:img('1629203849820-fdd70d49c38e')},
 {id:10,name:'Brownie con helado',cat:'Postres',price:4.5,desc:'Brownie tibio de chocolate con helado de vainilla.',image:img('1564355808539-22f0e7d0ad89')},
];
const cats=['Populares','Hamburguesas','Pizzas','Platos','Bebidas','Postres'];
const money=n=>`$${n.toFixed(2)}`;
function App(){
 const qrTable=new URLSearchParams(location.search).get('mesa'); const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('ug-cart')||'[]')); const [table,setTable]=useState(()=>qrTable?`Mesa ${qrTable}`:(localStorage.getItem('ug-table')||'Mesa 5'));
 const [cat,setCat]=useState('Populares'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[checkout,setCheckout]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[notes,setNotes]=useState(''),[name,setName]=useState('');
 useEffect(()=>localStorage.setItem('ug-cart',JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem('ug-table',table),[table]);
 const visible=useMemo(()=>products.filter(p=>(cat==='Populares'||p.cat===cat)&&p.name.toLowerCase().includes(search.toLowerCase())),[cat,search]);
 const count=cart.reduce((a,x)=>a+x.qty,0), total=cart.reduce((a,x)=>a+x.price*x.qty+(x.extras?.reduce((s,e)=>s+e.price,0)||0)*x.qty,0);
 const add=(p,qty=1,extras=[],special='')=>{if(!p){setSelected(null);return}setCart(c=>[...c,{...p,uid:Date.now()+Math.random(),qty,extras,special}]);setSelected(null)};
 const reset=()=>{setCart([]);setSent(false);setCheckout(false);setCat('Populares');};
 if(sent)return <div className="success"><div className="success-icon"><Check size={34}/></div><span className="eyebrow">PEDIDO CONFIRMADO</span><h1>¡Pedido enviado!</h1><p className="order-no">Pedido #1042</p><div className="receipt"><div><span>Mesa</span><strong>{table}</strong></div><p>Tu pedido fue enviado correctamente a cocina.</p><div className="steps"><b>Recibido</b><i></i><span>Preparando</span><i></i><span>Listo</span></div></div><p className="demo-note">Esta es una demostración. No se realizó ningún pedido real.</p><button className="primary" onClick={reset}>Volver al menú</button></div>;
 if(checkout)return <Checkout cart={cart} total={total} table={table} setTable={setTable} name={name} setName={setName} notes={notes} setNotes={setNotes} back={()=>setCheckout(false)} send={()=>{setBusy(true);setTimeout(()=>{setBusy(false);setSent(true)},1000)}} busy={busy}/>;
 return <><header><div className="brand"><div className="logo">UG</div><div><strong>Urban Grill</strong><small><span className="dot"></span> Abierto ahora</small></div></div><span className="demo-pill"><Sparkles size={13}/> Demo interactiva</span></header><main><section className="hero"><div><span className="eyebrow">BURGERS · PIZZAS · GOOD TIMES</span><h1>Elige algo<br/><em>delicioso.</em></h1><p>Comida urbana hecha al momento, directo a tu mesa.</p></div><div className="hero-card"><Clock3 size={16}/> 20–35 min</div></section><div className="table-row"><MapPin size={17}/><span>Estás en</span><select value={table} onChange={e=>setTable(e.target.value)}><option>Mesa 5</option><option>Mesa 1</option><option>Mesa 2</option><option>Mesa 3</option><option>Para llevar</option></select><ChevronRight size={16}/></div><div className="search"><Search size={18}/><input placeholder="¿Qué se te antoja?" value={search} onChange={e=>setSearch(e.target.value)}/></div><nav className="cats">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</nav><div className="section-title"><h2>{cat}</h2><span>{visible.length} opciones</span></div><div className="grid">{visible.map(p=><Product p={p} onClick={()=>setSelected(p)} key={p.id}/>)}</div></main>{count>0&&<button className="cart-bar" onClick={()=>setCheckout(true)}><span><ShoppingBag size={19}/><b>Ver pedido</b><small>{count} {count===1?'producto':'productos'}</small></span><strong>{money(total)} <ChevronRight size={19}/></strong></button>}{selected&&<ProductModal p={selected} add={add}/>}<button className="reset" onClick={reset} title="Reiniciar demo"><RotateCcw size={14}/></button></>;
}
function Product({p,onClick}){return <article className="product" onClick={onClick}><div className="photo"><img src={p.image} onError={e=>e.currentTarget.src='https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80'}/><button><Plus size={18}/></button></div><div className="product-info"><h3>{p.name}</h3><p>{p.desc}</p><strong>{money(p.price)}</strong></div></article>}
function ProductModal({p,add}){const [qty,setQty]=useState(1),[special,setSpecial]=useState(''),[term,setTerm]=useState('3/4'),[extras,setExtras]=useState([]);const toggle=e=>setExtras(x=>x.some(y=>y.name===e.name)?x.filter(y=>y.name!==e.name):[...x,e]);const sum=p.price+extras.reduce((a,e)=>a+e.price,0);return <div className="overlay"><div className="sheet"><button className="close" onClick={()=>add(null,0)}>×</button><img className="modal-img" src={p.image}/><div className="modal-body"><span className="eyebrow">{p.cat}</span><h2>{p.name}</h2><p>{p.desc}</p>{p.cat==='Hamburguesas'&&<><label>Término de carne</label><div className="options">{['Medio','3/4','Bien cocido'].map(x=><button className={term===x?'chosen':''} onClick={()=>setTerm(x)} key={x}>{term===x&&<Check size={13}/>} {x}</button>)}</div><label>Extras</label><div className="checks">{[{name:'Queso',price:1},{name:'Tocino',price:1.5},{name:'Papas',price:2}].map(e=><button className={extras.some(x=>x.name===e.name)?'checked':''} onClick={()=>toggle(e)} key={e.name}>{e.name}<span>+{money(e.price)}</span></button>)}</div></>}<label>Notas especiales <span>(opcional)</span></label><textarea placeholder="Ej. Sin cebolla, por favor" value={special} onChange={e=>setSpecial(e.target.value)}/><div className="modal-foot"><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={16}/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus size={16}/></button></div><button className="primary" onClick={()=>add(p,qty,[...extras,...(p.cat==='Hamburguesas'?[{name:`Término: ${term}`,price:0}]:[])],special)}>Agregar al pedido · {money(sum*qty)}</button></div></div></div></div>}
function Checkout({cart,total,table,setTable,name,setName,notes,setNotes,back,send,busy}){return <div className="checkout"><button className="back" onClick={back}><ArrowLeft size={18}/> Volver al menú</button><span className="eyebrow">RESUMEN</span><h1>Tu pedido</h1><div className="summary">{cart.map((x,i)=><div className="line" key={i}><div><b>{x.qty}× {x.name}</b>{x.extras?.length>0&&<small> + {x.extras.map(e=>e.name).join(', ')}</small>}{x.special&&<small>“{x.special}”</small>}</div><strong>{money((x.price+(x.extras?.reduce((a,e)=>a+e.price,0)||0))*x.qty)}</strong></div>)}<div className="total"><span>Total</span><strong>{money(total)}</strong></div></div><label>Mesa<select value={table} onChange={e=>setTable(e.target.value)}><option>Mesa 5</option><option>Mesa 1</option><option>Mesa 2</option><option>Mesa 3</option></select></label><label>Nombre <span>(opcional)</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="¿A nombre de quién?"/></label><label>Notas para el restaurante <span>(opcional)</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Alguna indicación especial..."/></label><button className="primary send" onClick={send} disabled={busy}>{busy?'Enviando pedido…':'Enviar pedido · '+money(total)}</button></div>}
function Share(){const [qr,setQr]=useState(''),[copied,setCopied]=useState(false),[table,setTable]=useState('5');const url=window.location.origin+appPath(`demo?mesa=${table}`);useEffect(()=>{QRCode.toDataURL(url,{width:900,margin:2,color:{dark:'#17221d',light:'#fffdf8'}}).then(setQr)},[url]);return <div className="share"><div className="share-brand"><div className="logo">UG</div><span>Urban Grill</span></div><span className="eyebrow">CENTRO DE COMPARTIR</span><h1>Un QR para<br/><em>cada mesa.</em></h1><p>Al escanearlo, el pedido queda asociado automáticamente a la mesa seleccionada.</p><label className="share-select">Generar QR para <select value={table} onChange={e=>setTable(e.target.value)}>{['1','2','3','4','5','6','7','8','Para llevar'].map(x=><option key={x} value={x}>{x==='Para llevar'?x:`Mesa ${x}`}</option>)}</select></label>{qr&&<img className="qr" src={qr}/>}<h3>Escanea para pedir desde {table==='Para llevar'?'tu celular':`la Mesa ${table}`}</h3><code>{url}</code><div className="share-actions"><button onClick={()=>{navigator.clipboard.writeText(url);setCopied(true)}}><Copy size={16}/> {copied?'Copiado':'Copiar enlace'}</button><a href={qr} download={`urban-grill-mesa-${table}.png`}><Download size={16}/> Descargar QR</a></div><a className="preview" href={appPath('demo/admin')}>Configurar menú y mesas <ChevronRight size={16}/></a></div>}
function Admin(){const [tab,setTab]=useState('overview');return <div className="admin"><header><div className="brand"><div className="logo">UG</div><div><strong>Urban Grill</strong><small>Centro de control</small></div></div><a className="demo-pill" href={appPath('demo')}>Ver menú <ChevronRight size={13}/></a></header><main><span className="eyebrow">PANEL DE DEMOSTRACIÓN</span><h1 className="admin-title">Todo listo para<br/><em>vender más.</em></h1><div className="admin-tabs">{[['overview','Resumen'],['menu','Menú'],['tables','Mesas']].map(([x,l])=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{l}</button>)}</div>{tab==='overview'&&<><div className="stat-grid"><div><span>Pedidos hoy</span><b>24</b><small>+18% esta semana</small></div><div><span>Ticket promedio</span><b>$18.40</b><small>Urban Grill</small></div><div><span>Mesas activas</span><b>8/12</b><small>4 disponibles</small></div></div><section className="admin-card"><div><h2>Comparte tu demo</h2><p>Genera un QR específico por mesa para que el cliente vea exactamente cómo funciona.</p></div><a className="primary admin-button" href={appPath('demo/share')}>Abrir centro de QR <ChevronRight size={16}/></a></section><section className="admin-card"><h2>Pedidos recientes</h2>{['#1041 · Mesa 3',' #1040 · Mesa 8',' #1039 · Mesa 5'].map((x,i)=><div className="admin-row" key={x}><span>{x}</span><b>{i===0?'Preparando':'Listo'}</b><strong>{['$24.50','$16.00','$32.00'][i]}</strong></div>)}</section></>}{tab==='menu'&&<section className="admin-card"><h2>Menú publicado</h2><p>10 productos · 6 categorías · Visible para tus clientes</p>{products.slice(0,5).map(p=><div className="admin-row" key={p.id}><span>{p.name}</span><b className="on">Publicado</b><strong>{money(p.price)}</strong></div>)}<button className="primary admin-button" onClick={()=>alert('En una versión conectada aquí podrás editar productos, fotos y precios.')}>+ Agregar producto</button></section>}{tab==='tables'&&<section className="admin-card"><h2>Mesas y códigos QR</h2><p>Cada código abre el menú con la mesa identificada automáticamente.</p>{['1','2','3','4','5','6','7','8'].map(n=><div className="admin-row" key={n}><span><MapPin size={14}/> Mesa {n}</span><b className="on">QR activo</b><a href={appPath(`demo?mesa=${n}`)}>Probar <ChevronRight size={14}/></a></div>)}</section>}</main></div>}
function Router(){const p=location.pathname.replace(/\/$/,'');return p==='/demo/share'?<Share/>:p==='/demo/admin'?<Admin/>:<App/>}createRoot(document.getElementById('root')).render(<Router/>);
